[package]
name = "kapsule"
version = "0.1.0"
edition = "2021"

# [build]
# target = "aarch64-unknown-linux-gnu" 

[dependencies]
nix = { version = "0.29.0", features=["process", "sched", "hostname", "mount"] }
